### ISSUE TITLE
question: about singularity

### ISSUE THREAD

**Issue by AlbertTan404** [cshizhe/hiveformer#1]
Hi there!

I'm new to singularity. I wonder in which way can I enter the pulled .sif file? Through `singularity bash` or `singularity run `?

Thanks.

**Comment by AlbertTan404** [comment]
Cuz I just ran into "/bin/sh: 1: glxgears: not found" after I entered `singularity run vlc_rlbench.sif_latest.sif` and GPT-4 told me that "The error message "/bin/sh: 1: glxgears: not found" indicates that the command glxgears is not found in the Singularity container (my_image.sif) that you are trying to run. The issue is not with the host but with the image itself."

**Comment by cshizhe** [comment]
You could use `singularity shell` to use the image in interactive mode.
