### ISSUE TITLE
Unable to open training data.

### ISSUE THREAD

**Issue by Project-NSE** [cshizhe/hiveformer#5]
How can I open the files that I have downloaded from " https://www.dropbox.com/s/zrth410b4voi4ut/train_dataset.tar.gz?dl=0 "? They have .mdb extension. When I try to open it using "Microsoft Access" I got the error "Unrecognized database format".

**Comment by cshizhe** [comment]
Hi, they are lmdb files (https://lmdb.readthedocs.io/en/release/).
