### ISSUE TITLE
Questions about the coordinate range of the environment

### ISSUE THREAD

**Issue by SatireY** [cshizhe/hiveformer#6]
Great job!
I have also done some research work on RLBench, and would like to ask you what is the maximum and minimum range of Cartesian coordinates p_t in your actions?

**Comment by cshizhe** [comment]
Hi, we don't explicitly constrain the bounds of the action p_t in our model. As shown [here](https://github.com/vlc-robot/hiveformer/blob/main/models/transformer_unet.py#L225), the xt_offset is the regression result.
