### ISSUE TITLE
Questions about the details of the experiment

### ISSUE THREAD

**Issue by SatireY** [cshizhe/hiveformer#7]
How exactly is your multitasking experiment set up? This sentence I saw in the paper puzzled me: "but each task has a unique variation" Does it mean that only one variant is used for each task?
Also, in the multi-variant experiment, did you use 200 variants in each of the two tasks? What is the upper limit for each task variant of RLBench?

**Comment by cshizhe** [comment]
Yes, we only use the first variation for each task in the multi-task setup, and use all the variations provided by RLBench in the multi-variant setup. The number of variations per task can be checked in the [RLBench repo](https://github.com/rjgpinel/RLBench).
