### ISSUE TITLE
Dataset link out of date

### ISSUE THREAD

**Issue by NishanthARao** [cshizhe/hiveformer#8]
Hello, it seems that the dropbox link for the dataset isn't working / outdated. Would it be possible to regenerate a new link?

Thank you!

**Comment by rgpinel** [comment]
Hello,

@NishanthARao thank you for noticing this!

We have updated the README with a new link with the datasets for 10 and 74 tasks: https://drive.google.com/drive/folders/1BCvGrTK_cLkMuF9XR40Xx_QciXM3htwh?usp=drive_link

Thank you. I close this issue.
